### ISSUE TITLE
[Vulnerability] Direct Style Manipulation

### ISSUE THREAD

**Issue by Neo-Harsh25** [jiveshkalra/SecureHack-Quest-TechBuzz#132]
# Description of the Vulnerability
Employing style.Comparing display to CSS classes might help you manage it more easily.

# Screen Shot of the Vulnerable Code
![image](https://github.com/user-attachments/assets/909b218d-1ae9-4b46-9a7f-f1203b54b490)

# Impact of the vulnerability
4/5

# Recommended Steps to resolve it?
Utilize CSS Classes to Manage Visibility
Use CSS classes to regulate visibility rather than modifying style.display directly. By separating style from logic, this improves code maintainability.
# School Name 
GD Goenka Sector 10A

**Comment by DIY-It-All** [comment]
Competition is for cyber security, not UI
