### ISSUE TITLE
 Inconsistent Index Access 

### ISSUE THREAD

**Issue by A-965** [jiveshkalra/SecureHack-Quest-TechBuzz#153]
Problem:
The blog_data index is accessed with blog_data[9] to update the view count, but there is no guarantee that the structure of blog_data will always be as expected. This index might be out of range or incorrect if the database schema changes or if the query returns columns in a different order.

**Comment by DIY-It-All** [comment]
since we use sql, this is guaranteed. The structure is hard coded in sql table.
