### ISSUE TITLE
missing import "error" import flusk can not be resolved

### ISSUE THREAD

**Issue by Jitesh-6** [jiveshkalra/SecureHack-Quest-TechBuzz#16]
# Description of the Vulnerability

# Screen Shot of the Vulnerable Code
![Screenshot 2024-08-02 100456](https://github.com/user-attachments/assets/4cc5ebcd-d207-45e6-976b-201b0a75ab76)

# Impact of the vulnerability
Rate the vulnerability from 1 to 5 , with 5 being the most critical vulnerability which needs to be resolved asap.
2

# Recommended Steps to resolve it?
Recommend steps to resolve it if you can, else you may leave this empty

# School Name 
Enter your school name that you filled in form
rps-89

**Comment by DIY-It-All** [comment]
pip install flask
