### ISSUE TITLE
[Vulnerability] Broken Links in 'index.html'

### ISSUE THREAD

**Issue by Hardik-Sharma-121123** [jiveshkalra/SecureHack-Quest-TechBuzz#167]
# Description of the Vulnerability
The href attribute in the <a> tags are being used with single curly braces { }. this would lead to undynamic images.

# Screen Shot of the Vulnerable Code
![image](https://github.com/user-attachments/assets/b6fd8b53-e649-451c-a173-5453667abc2f)

# Impact of the vulnerability
4/5 [needs to be resolved on priority ]

# Recommended Steps to resolve it?
Can use double curly braces {{ }}

# School Name 
DAV PRATAP VIHAR

**Comment by DIY-It-All** [comment]
it's resolved with the new commits, just fetch the latest commits
