### ISSUE TITLE
hardcoded paths

### ISSUE THREAD

**Issue by Yashverm** [jiveshkalra/SecureHack-Quest-TechBuzz#178]
# Description of the Vulnerability
paths may differ between development, testing, and production environments. hardcoding paths can lead to environment-specific issues , exposing sensitive paths or information in the code , revealing the directory structure or sensitive files

# Screen Shot of the Vulnerable Code
blogs.html

# Impact of the vulnerability
3/5

# Recommended Steps to resolve it?
environment-specific configuration files or environment variables to set paths based on the current environment , store sensitive paths in secure configuration files or environment variables , and avoid exposing them in the code

# School Name 
Lions Public School

**Comment by jiveshkalra** [comment]
where are the hardcoded paths?? 
if you have any example of it re-open this issue with that

**Comment by Ambrish2908** [comment]
The issue has been opened, pl check it
