### ISSUE TITLE
hardcoded paths(re-opened)

### ISSUE THREAD

**Issue by Yashverm** [jiveshkalra/SecureHack-Quest-TechBuzz#205]
# Description of the Vulnerability
paths may differ between development, testing, and production environments. hardcoding paths can lead to environment-specific issues , exposing sensitive paths or information in the code , revealing the directory structure or sensitive files

# Screen Shot of the Vulnerable Code
blogs.html
![7](https://github.com/user-attachments/assets/ab44acd6-e6cc-492a-956c-0b16e3f6fb14)
![8](https://github.com/user-attachments/assets/b9ca6176-52a6-47ba-b1d3-a4893b9c7940)

# Impact of the vulnerability
3/5

# Recommended Steps to resolve it?
environment-specific configuration files or environment variables to set paths based on the current environment , store sensitive paths in secure configuration files or environment variables , and avoid exposing them in the code

# School Name 
Lions Public School

**Comment by jiveshkalra** [comment]
the screenshots you have given are not hardcoded paths, they are of dynamic paths only
