### ISSUE TITLE
[Vulnerability] Error Handling & Feedback

### ISSUE THREAD

**Issue by Hardik-Sharma-121123** [jiveshkalra/SecureHack-Quest-TechBuzz#48]
# Description of the Vulnerability
The error handling in the fetch response is basic and relies on alerts, which aren't user-friendly. It also does not handle cases where the request fails entirely. For example, network issues.

# Screen Shot of the Vulnerable Code
![image](https://github.com/user-attachments/assets/07f72e1f-10c6-4a25-9d75-7e99f3cc955d)
-in 'create_blog.html'
# Impact of the vulnerability
5/5 [needs to be resolved ASAP as its regarding front-end]

# Recommended Steps to resolve it?
Modification Suggestion:
![image](https://github.com/user-attachments/assets/d7d40793-4475-4cf9-b960-97ab15d821b9)

# School Name 
DAV PRATAP VIHAR

**Comment by DIY-It-All** [comment]
It's a cyber security event, cosmetic fixes are invalid.
