### ISSUE TITLE
[Vulnerability]Error Handling

### ISSUE THREAD

**Issue by moonz-core** [jiveshkalra/SecureHack-Quest-TechBuzz#54]
# Description of the Vulnerability
 While there are some try-except blocks, the error handling is not robust enough.
# Screen Shot of the Vulnerable Code
Add some screenshots of the part of code thats vulnerable

# Impact of the vulnerability
4/5

# Recommended Steps to resolve it?
 Provide more informative error messages to the user without revealing sensitive information.
# School Name 
DPS maruti kunj

**Comment by DIY-It-All** [comment]
be more specific and send send screenshots

**Comment by DIY-It-All** [comment]
then raise issue again
