### ISSUE TITLE
Error Handling in Database Operation

### ISSUE THREAD

**Issue by K-0252** [jiveshkalra/SecureHack-Quest-TechBuzz#95]
Vulnerability Description: 

The database do not handle exceptions , which lead to inconsistent output or the application is crashed

Impact of Vulnerability:

8/10

How to solve :
1) gather user data 
2) update blog view
3) insert new user data 

NAME OF SCHOOL: DAVPPS GURUGRAM

**Comment by DIY-It-All** [comment]
be more specific.
